// =====================================================
// SmartCampus Localization / Translation Dictionary
// Supports: English (en-IN), Telugu (te-IN), Hindi (hi-IN), Tamil (ta-IN), Kannada (kn-IN)
// =====================================================

export const TRANSLATIONS = {
  'en-IN': {
    // Navigation
    'nav_dashboard': 'Dashboard',
    'nav_submit': 'Submit Complaint',
    'nav_complaints': 'Complaints',
    'nav_heatmap': 'Campus Heatmap',
    'nav_leaderboard': 'Leaderboard',
    'nav_profile': 'Profile',
    'nav_analytics': 'Analytics',
    'nav_admin': 'Admin Panel',
    'nav_dept_admins': 'Dept Admins',
    'nav_logout': 'Logout',

    // Dashboard
    'dash_welcome': 'Welcome back',
    'dash_subtitle': 'Campus problem detection and automation dashboard.',
    'dash_total': 'Total Complaints',
    'dash_open': 'Open Issues',
    'dash_in_progress': 'In Progress',
    'dash_resolved': 'Resolved Complaints',
    'dash_recent': 'Recent Complaints',
    'dash_view_all': 'View All',
    'dash_no_telemetry': 'No telemetry data available.',
    'dash_no_complaints': 'No recent complaints filed.',
    'dash_intelligence': 'SmartCampus Intelligence',
    'dash_intel_stable': 'All campus issues are currently stable.',
    'dash_intel_active': 'complaints are awaiting immediate triage.',
    'dash_most_reported': 'Most reported category',
    'dash_category_distribution': 'Category Distribution',
    'dash_complaint_trend': 'Complaint Trend (This Week)',
    'dash_priority_breakdown': 'Priority Breakdown',
    'dash_complaints_by_category': 'Complaints by Category',

    // Submit Complaint
    'sub_header': 'Submit New Complaint',
    'sub_subtitle': 'Describe your issue and let AI classify and prioritize it automatically.',
    'sub_title_label': 'Complaint Title',
    'sub_title_placeholder': 'Brief title describing the issue',
    'sub_desc_label': 'Detailed Description',
    'sub_desc_placeholder': 'Describe the problem in detail. Include what, where, when, and severity. The more detail you provide, the better the AI classification will be...',
    'sub_location_label': 'Location',
    'sub_location_placeholder': 'Select location of the issue',
    'sub_image_label': 'Attach Image (optional)',
    'sub_btn_analyze': 'Analyze with AI',
    'sub_btn_analyzing': 'Analyzing with GenAI...',
    'sub_btn_submit': 'Submit Complaint',
    'sub_btn_submitting': 'Submitting...',
    'sub_voice_lang': 'Spoken Language',
    'sub_voice_title': 'Voice Assistant',
    'sub_voice_listen': '🔴 Listening... Speak now',
    'sub_voice_processing': '⏳ AI processing...',
    'sub_voice_stop': 'Speak in any language — tap mic to stop',
    'sub_voice_captured': 'Speech captured! Translating in background...',
    'sub_voice_tap': 'Tap the mic and speak your complaint in any language',
    'sub_voice_listening_msg': '🎙️ Listening via Deepgram... Speak now',
    'sub_ai_panel_title': 'AI Analysis',
    'sub_ai_panel_desc': 'Enter your complaint description and click "Analyze with AI" to get automatic classification, priority prediction, and recommended action plan.',
    'sub_ai_results': '🤖 AI Analysis Results',
    'sub_ai_confidence': 'confidence',
    'sub_ai_predicted_cat': 'Predicted Category',
    'sub_ai_priority': 'Priority Level',
    'sub_ai_summary': 'AI Summary',
    'sub_ai_sops': 'Retrieved SOPs (RAG)',
    'sub_ai_action_plan': 'Generated Action Plan',

    // Profile
    'prof_header': 'Profile Settings',
    'prof_lang_label': 'Preferred Website Language',
    'prof_save': 'Save Changes',
    'prof_saving': 'Saving...',
    'prof_details': 'Account Details',
    'prof_email': 'Email',
    'prof_fullname': 'Full Name',
    'prof_dept': 'Department',
    'prof_id': 'ID Number',
    'prof_phone': 'Phone',
    'prof_since': 'Member Since',
    'prof_edit': 'Edit Profile',
    'prof_cancel': 'Cancel',
    'prof_administrator': 'Administrator',
    'prof_student': 'Student',
    'prof_staff': 'Staff',
    'prof_not_set': 'Not set'
  },
  'te-IN': {
    // Navigation
    'nav_dashboard': 'డాష్‌బోర్డ్',
    'nav_submit': 'ఫిర్యాదు చేయండి',
    'nav_complaints': 'ఫిర్యాదులు',
    'nav_heatmap': 'క్యాంపస్ హీట్‌మ్యాప్',
    'nav_leaderboard': 'లీడర్‌బోర్డ్',
    'nav_profile': 'ప్రొఫైల్',
    'nav_analytics': 'విశ్లేషణలు',
    'nav_admin': 'అడ్మిన్ ప్యానెల్',
    'nav_dept_admins': 'విభాగం నిర్వాహకులు',
    'nav_logout': 'లాగ్ అవుట్',

    // Dashboard
    'dash_welcome': 'మళ్ళీ స్వాగతం',
    'dash_subtitle': 'క్యాంపస్ సమస్య గుర్తింపు మరియు ఆటోమేషన్ డాష్‌బోర్డ్.',
    'dash_total': 'మొత్తం ఫిర్యాదులు',
    'dash_open': 'ఓపెన్ సమస్యలు',
    'dash_in_progress': 'ప్రక్రియలో ఉన్నవి',
    'dash_resolved': 'పరిష్కరించబడినవి',
    'dash_recent': 'ఇటీవలి ఫిర్యాదులు',
    'dash_view_all': 'అన్నీ చూడండి',
    'dash_no_telemetry': 'టెలిమెట్రీ డేటా అందుబాటులో లేదు.',
    'dash_no_complaints': 'ఇటీవల ఎటువంటి ఫిర్యాదులు నమోదు కాలేదు.',
    'dash_intelligence': 'స్మార్ట్‌క్యాంపస్ ఇంటెలిజెన్స్',
    'dash_intel_stable': 'క్యాంపస్ సమస్యలన్నీ ప్రస్తుతం స్థిరంగా ఉన్నాయి.',
    'dash_intel_active': 'ఫిర్యాదులు తక్షణ పరిశీలన కోసం వేచి ఉన్నాయి.',
    'dash_most_reported': 'ఎక్కువగా నమోదైన వర్గం',
    'dash_category_distribution': 'వర్గం పంపిణీ',
    'dash_complaint_trend': 'ఫిర్యాదుల ధోరణి (ఈ వారం)',
    'dash_priority_breakdown': 'ప్రాధాన్యత విభజన',
    'dash_complaints_by_category': 'వర్గం వారీగా ఫిర్యాదులు',

    // Submit Complaint
    'sub_header': 'కొత్త ఫిర్యాదు చేయండి',
    'sub_subtitle': 'మీ సమస్యను వివరించండి, AI స్వయంచాలకంగా వర్గీకరించి ప్రాధాన్యతను గుర్తిస్తుంది.',
    'sub_title_label': 'ఫిర్యాదు శీర్షిక',
    'sub_title_placeholder': 'సమస్యను వివరించే చిన్న శీర్షిక',
    'sub_desc_label': 'వివరణాత్మక వివరణ',
    'sub_desc_placeholder': 'సమస్యను వివరంగా వివరించండి. ఏమిటి, ఎక్కడ, ఎప్పుడు మరియు తీవ్రతను చేర్చండి. ఎక్కువ వివరాలు ఇస్తే AI వర్గీకరణ అంత బాగుంటుంది...',
    'sub_location_label': 'స్థలం (లొకేషన్)',
    'sub_location_placeholder': 'సమస్య ఉన్న స్థలాన్ని ఎంచుకోండి',
    'sub_image_label': 'చిత్రాన్ని జతచేయండి (ఐచ్ఛికం)',
    'sub_btn_analyze': 'AI తో విశ్లేషించు',
    'sub_btn_analyzing': 'GenAI తో విశ్లేషిస్తోంది...',
    'sub_btn_submit': 'ఫిర్యాదును సమర్పించు',
    'sub_btn_submitting': 'సమర్పిస్తోంది...',
    'sub_voice_lang': 'మాట్లాడే భాష',
    'sub_voice_title': 'వాయిస్ అసిస్టెంట్',
    'sub_voice_listen': '🔴 వింటోంది... మాట్లాడండి',
    'sub_voice_processing': '⏳ AI ప్రాసెస్ చేస్తోంది...',
    'sub_voice_stop': 'ఏ భాషలోనైనా మాట్లాడండి — ఆపడానికి మైక్ నొక్కండి',
    'sub_voice_captured': 'మాటలు రికార్డ్ అయ్యాయి! నేపధ్యంలో అనువదిస్తోంది...',
    'sub_voice_tap': 'మైక్ నొక్కి ఏ భాషలోనైనా మీ ఫిర్యాదును మాట్లాడండి',
    'sub_voice_listening_msg': '🎙️ డీప్‌గ్రామ్ ద్వారా వింటోంది... మాట్లాడండి',
    'sub_ai_panel_title': 'AI విశ్లేషణ',
    'sub_ai_panel_desc': 'మీ ఫిర్యాదు వివరాలను నమోదు చేసి, స్వయంచాలక వర్గీకరణ, ప్రాధాన్యత అంచనా మరియు సిఫార్సు చేసిన కార్యాచరణ ప్రణాళికను పొందడానికి "AI తో విశ్లేషించు" క్లిక్ చేయండి.',
    'sub_ai_results': '🤖 AI విశ్లేషణ ఫలితాలు',
    'sub_ai_confidence': 'విశ్వసనీయత',
    'sub_ai_predicted_cat': 'అంచనా వేసిన వర్గం',
    'sub_ai_priority': 'ప్రాధాన్యత స్థాయి',
    'sub_ai_summary': 'AI సారాంశం',
    'sub_ai_sops': 'లభించిన SOPలు (RAG)',
    'sub_ai_action_plan': 'రూపొందించిన కార్యాచరణ ప్రణాళిక',

    // Profile
    'prof_header': 'ప్రొఫైల్ సెట్టింగ్స్',
    'prof_lang_label': 'ఇష్టపడే వెబ్‌సైట్ భాష',
    'prof_save': 'మార్పులను సేవ్ చేయి',
    'prof_saving': 'సేవ్ చేస్తోంది...',
    'prof_details': 'ఖాతా వివరాలు',
    'prof_email': 'ఇమెయిల్',
    'prof_fullname': 'పూర్తి పేరు',
    'prof_dept': 'విభాగం (డిపార్ట్‌మెంట్)',
    'prof_id': 'ఐడి నంబర్',
    'prof_phone': 'ఫోన్',
    'prof_since': 'సభ్యత్వం పొందిన తేదీ',
    'prof_edit': 'ప్రೊఫೈల్ సవరించు',
    'prof_cancel': 'రద్దు చేయి',
    'prof_administrator': 'నిర్వాహకుడు',
    'prof_student': 'विद्यार्थी (విద్యార్థి)',
    'prof_staff': 'సిబ్బంది',
    'prof_not_set': 'నమోదు కాలేదు'
  },
  'hi-IN': {
    // Navigation
    'nav_dashboard': 'डैशबोर्ड',
    'nav_submit': 'शिकायत दर्ज करें',
    'nav_complaints': 'शिकायतें',
    'nav_heatmap': 'कैंपस हीटमैप',
    'nav_leaderboard': 'लीडरबोर्ड',
    'nav_profile': 'प्रोफ़ाइल',
    'nav_analytics': 'विश्लेषण',
    'nav_admin': 'एडमिन पैनल',
    'nav_dept_admins': 'विभाग एडमिन',
    'nav_logout': 'लॉग आउट',

    // Dashboard
    'dash_welcome': 'आपका स्वागत है',
    'dash_subtitle': 'कैंपस समस्या पहचान और स्वचालन डैशबोर्ड।',
    'dash_total': 'कुल शिकायतें',
    'dash_open': 'खुली समस्याएं',
    'dash_in_progress': 'प्रगति पर है',
    'dash_resolved': 'सुलझाई गई शिकायतें',
    'dash_recent': 'हाल की शिकायतें',
    'dash_view_all': 'सभी देखें',
    'dash_no_telemetry': 'कोई टेलीमेट्री डेटा उपलब्ध नहीं है।',
    'dash_no_complaints': 'हाल ही में कोई शिकायत दर्ज नहीं की गई है।',
    'dash_intelligence': 'स्मार्टकैंपस इंटेलिजेंस',
    'dash_intel_stable': 'कैंपस की सभी समस्याएं वर्तमान में स्थिर हैं।',
    'dash_intel_active': 'शिकायतें तत्काल समीक्षा की प्रतीक्षा कर रही हैं।',
    'dash_most_reported': 'सर्वाधिक रिपोर्ट की गई श्रेणी',
    'dash_category_distribution': 'श्रेणी वितरण',
    'dash_complaint_trend': 'शिकायत रुझान (इस सप्ताह)',
    'dash_priority_breakdown': 'प्राथमिकता वर्गीकरण',
    'dash_complaints_by_category': 'श्रेणी के अनुसार शिकायतें',

    // Submit Complaint
    'sub_header': 'नई शिकायत दर्ज करें',
    'sub_subtitle': 'अपनी समस्या का वर्णन करें, AI स्वचालित रूप से इसका वर्गीकरण और प्राथमिकता तय करेगा।',
    'sub_title_label': 'शिकायत का शीर्षक',
    'sub_title_placeholder': 'समस्या का संक्षिप्त विवरण देने वाला शीर्षक',
    'sub_desc_label': 'विस्तृत विवरण',
    'sub_desc_placeholder': 'समस्या का विस्तार से वर्णन करें। क्या, कहाँ, कब और गंभीरता शामिल करें। जितनी अधिक जानकारी होगी, AI वर्गीकरण उतना ही बेहतर होगा...',
    'sub_location_label': 'स्थान',
    'sub_location_placeholder': 'समस्या का स्थान चुनें',
    'sub_image_label': 'छवि संलग्न करें (वैकल्पिक)',
    'sub_btn_analyze': 'AI से विश्लेषण करें',
    'sub_btn_analyzing': 'GenAI से विश्लेषण हो रहा है...',
    'sub_btn_submit': 'शिकायत जमा करें',
    'sub_btn_submitting': 'जमा हो रहा है...',
    'sub_voice_lang': 'बोली जाने वाली भाषा',
    'sub_voice_title': 'आवाज सहायक (वॉयस असिस्टेंट)',
    'sub_voice_listen': '🔴 सुन रहा है... बोलें',
    'sub_voice_processing': '⏳ AI प्रोसेस कर रहा है...',
    'sub_voice_stop': 'किसी भी भाषा में बोलें — रोकने के लिए माइक दबाएं',
    'sub_voice_captured': 'भाषण रिकॉर्ड हो गया! पृष्ठभूमि में अनुवाद हो रहा है...',
    'sub_voice_tap': 'माइक दबाएं और अपनी शिकायत किसी भी भाषा में बोलें',
    'sub_voice_listening_msg': '🎙️ डीपग्राम के माध्यम से सुन रहा है... बोलें',
    'sub_ai_panel_title': 'AI विश्लेषण',
    'sub_ai_panel_desc': 'अपनी शिकायत का विवरण दर्ज करें और स्वचालित वर्गीकरण, प्राथमिकता पूर्वानुमान और अनुशंसित कार्य योजना प्राप्त करने के लिए "AI से विश्लेषण करें" पर क्लिक करें।',
    'sub_ai_results': '🤖 AI विश्लेषण परिणाम',
    'sub_ai_confidence': 'आत्मविश्वास',
    'sub_ai_predicted_cat': 'पूर्वानुमानित श्रेणी',
    'sub_ai_priority': 'प्राथमिकता स्तर',
    'sub_ai_summary': 'AI सारांश',
    'sub_ai_sops': 'प्राप्त SOPs (RAG)',
    'sub_ai_action_plan': 'उत्पन्न कार्य योजना',

    // Profile
    'prof_header': 'प्रोफ़ाइल सेटिंग्स',
    'prof_lang_label': 'पसंदीदा वेबसाइट भाषा',
    'prof_save': 'बदलाव सहेजें',
    'prof_saving': 'सहेज रहा है...',
    'prof_details': 'खाता विवरण',
    'prof_email': 'ईमेल',
    'prof_fullname': 'पूरा नाम',
    'prof_dept': 'विभाग',
    'prof_id': 'आईडी नंबर',
    'prof_phone': 'फ़ोन',
    'prof_since': 'सदस्यता की तिथि',
    'prof_edit': 'प्रोफ़ाइल संपादित करें',
    'prof_cancel': 'रद्द करें',
    'prof_administrator': 'प्रशासक',
    'prof_student': 'छात्र',
    'prof_staff': 'कर्मचारी',
    'prof_not_set': 'सेट नहीं है'
  },
  'ta-IN': {
    // Navigation
    'nav_dashboard': 'டாஷ்போர்டு',
    'nav_submit': 'புகார் சமர்ப்பிக்கவும்',
    'nav_complaints': 'புகார்கள்',
    'nav_heatmap': 'வளாக ஹீட்மேப்',
    'nav_leaderboard': 'லீடர்போர்டு',
    'nav_profile': 'சுயவிவரம்',
    'nav_analytics': 'பகுப்பாய்வு',
    'nav_admin': 'நிர்வாக குழு',
    'nav_dept_admins': 'துறை நிர்வாகிகள்',
    'nav_logout': 'வெளியேறு',

    // Dashboard
    'dash_welcome': 'மீண்டும் வருக',
    'dash_subtitle': 'வளாக பிரச்சனை கண்டறிதல் மற்றும் ஆட்டோமேஷன் டாஷ்போர்டு.',
    'dash_total': 'மொத்த புகார்கள்',
    'dash_open': 'திறந்த சிக்கல்கள்',
    'dash_in_progress': 'செயல்பாட்டில் உள்ளது',
    'dash_resolved': 'தீர்க்கப்பட்ட புகார்கள்',
    'dash_recent': 'சமீபத்திய புகார்கள்',
    'dash_view_all': 'அனைத்தையும் பார்',
    'dash_no_telemetry': 'டெலிமெட்ரி தரவு எதுவும் கிடைக்கவில்லை.',
    'dash_no_complaints': 'சமீபத்தில் எந்த புகாரும் பதிவு செய்யப்படவில்லை.',
    'dash_intelligence': 'ஸ்மார்ட்வளாக அறிவுத்திறன்',
    'dash_intel_stable': 'அனைத்து வளாக சிக்கல்களும் தற்போது சீராக உள்ளன.',
    'dash_intel_active': 'புகார்கள் உடனடி மதிப்பீட்டிற்காக காத்திருக்கின்றன.',
    'dash_most_reported': 'அதிகம் புகாரளிக்கப்பட்ட வகை',
    'dash_category_distribution': 'வகை விநியோகம்',
    'dash_complaint_trend': 'புகார் போக்கு (இந்த வாரம்)',
    'dash_priority_breakdown': 'முன்னுரிமை முறிவு',
    'dash_complaints_by_category': 'வகை வாரியாக புகார்கள்',

    // Submit Complaint
    'sub_header': 'புதிய புகாரை சமர்ப்பிக்கவும்',
    'sub_subtitle': 'உங்கள் பிரச்சனையை விவரிக்கவும், AI தானாகவே வகைப்படுத்தி முன்னுரிமையை கணிக்கிறது.',
    'sub_title_label': 'புகார் தலைப்பு',
    'sub_title_placeholder': 'பிரச்சனையை விவரிக்கும் சிறு தலைப்பு',
    'sub_desc_label': 'விரிவான விளக்கம்',
    'sub_desc_placeholder': 'பிரச்சனையை விரிவாக விவரிக்கவும். என்ன, எங்கே, எப்போது மற்றும் தீவிரத்தன்மை ஆகியவற்றைச் சேர்க்கவும். கூடுதல் விவரங்களை வழங்கினால் AI வகைப்பாடு சிறப்பானதாக இருக்கும்...',
    'sub_location_label': 'இடம்',
    'sub_location_placeholder': 'பிரச்சனை உள்ள இடத்தை தேர்வு செய்யவும்',
    'sub_image_label': 'படத்தை இணைக்கவும் (விருப்பம்)',
    'sub_btn_analyze': 'AI உடன் பகுப்பாய்வு செய்',
    'sub_btn_analyzing': 'GenAI பகுப்பாய்வு செய்கிறது...',
    'sub_btn_submit': 'புகாரைச் சமர்ப்பி',
    'sub_btn_submitting': 'சமர்ப்பிக்கிறது...',
    'sub_voice_lang': 'பேசும் மொழி',
    'sub_voice_title': 'குரல் உதவியாளர்',
    'sub_voice_listen': '🔴 கேட்கிறது... பேசவும்',
    'sub_voice_processing': '⏳ AI செயலாக்குகிறது...',
    'sub_voice_stop': 'எந்த மொழியிலும் பேசவும் — நிறுத்த மைக்கை தட்டவும்',
    'sub_voice_captured': 'குரல் பதிவு செய்யப்பட்டது! பின்னணியில் மொழிபெயர்க்கிறது...',
    'sub_voice_tap': 'மைக்கை தட்டி உங்கள் புகாரை எந்த மொழியிலும் பேசவும்',
    'sub_voice_listening_msg': '🎙️ டீப்கிராம் மூலம் கேட்கிறது... பேசவும்',
    'sub_ai_panel_title': 'AI பகுப்பாய்வு',
    'sub_ai_panel_desc': 'உங்கள் புகார் விவரங்களை உள்ளிட்டு, தானியங்கி வகைப்பாடு, முன்னுரிமை கணிப்பு மற்றும் பரிந்துரைக்கப்பட்ட செயல் திட்டத்தை பெற "AI உடன் பகுப்பாய்வு செய்" என்பதைக் கிளிக் செய்யவும்.',
    'sub_ai_results': '🤖 AI பகுப்பாய்வு முடிவுகள்',
    'sub_ai_confidence': 'நம்பிக்கை',
    'sub_ai_predicted_cat': 'கணிக்கப்பட்ட வகை',
    'sub_ai_priority': 'முன்னுரிமை நிலை',
    'sub_ai_summary': 'AI சுருக்கம்',
    'sub_ai_sops': 'பெறப்பட்ட SOPகள் (RAG)',
    'sub_ai_action_plan': 'உருவாக்கப்பட்ட செயல் திட்டம்',

    // Profile
    'prof_header': 'சுயவிவர அமைப்புகள்',
    'prof_lang_label': 'விருப்பமான இணையதள மொழி',
    'prof_save': 'மாற்றங்களைச் சேமி',
    'prof_saving': 'சேமிக்கிறது...',
    'prof_details': 'கணக்கு விவரங்கள்',
    'prof_email': 'மின்னஞ்சல்',
    'prof_fullname': 'முழு பெயர்',
    'prof_dept': 'துறை',
    'prof_id': 'அடையாள எண்',
    'prof_phone': 'தொலைபேசி',
    'prof_since': 'உறுப்பினர் சேர்ந்த தேதி',
    'prof_edit': 'சுயவிவரத்தைத் திருத்து',
    'prof_cancel': 'ரத்து செய்',
    'prof_administrator': 'நிர்வாகி',
    'prof_student': 'மாணவர்',
    'prof_staff': 'பணியாளர்',
    'prof_not_set': 'அமைக்கப்படவில்லை'
  },
  'kn-IN': {
    // Navigation
    'nav_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav_submit': 'ದೂರು ಸಲ್ಲಿಸಿ',
    'nav_complaints': 'ದೂರುಗಳು',
    'nav_heatmap': 'ಕ್ಯಾಂಪಸ್ ಹೀಟ್‌ಮ್ಯಾಪ್',
    'nav_leaderboard': 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    'nav_profile': 'ಪ್ರೊಫೈಲ್',
    'nav_analytics': 'ವಿಶ್ಲೇಷಣೆಗಳು',
    'nav_admin': 'ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್',
    'nav_dept_admins': 'ವಿಭಾಗದ ನಿರ್ವಾಹಕರು',
    'nav_logout': 'ಲಾಗ್ ಔಟ್',

    // Dashboard
    'dash_welcome': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'dash_subtitle': 'ಕ್ಯಾಂಪಸ್ ಸಮಸ್ಯೆ ಪತ್ತೆ ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್.',
    'dash_total': 'ಒಟ್ಟು ದೂರುಗಳು',
    'dash_open': 'ತೆರೆದ ಸಮಸ್ಯೆಗಳು',
    'dash_in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'dash_resolved': 'ಪರಿಹರಿಸಲಾದ ದೂರುಗಳು',
    'dash_recent': 'ಇತ್ತೀಚಿನ ದೂರುಗಳು',
    'dash_view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    'dash_no_telemetry': 'ಟೆಲಿಮೆಟ್ರಿ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
    'dash_no_complaints': 'ಇತ್ತೀಚೆಗೆ ಯಾವುದೇ ದೂರುಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ.',
    'dash_intelligence': 'ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಂಪಸ್ ಇಂಟೆಲಿಜೆನ್ಸ್',
    'dash_intel_stable': 'ಎಲ್ಲಾ ಕ್ಯಾಂಪಸ್ ಸಮಸ್ಯೆಗಳು ಪ್ರಸ್ತುತ ಸ್ಥಿರವಾಗಿವೆ.',
    'dash_intel_active': 'ದೂರುಗಳು ತಕ್ಷಣದ ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯುತ್ತಿವೆ.',
    'dash_most_reported': 'ಹೆಚ್ಚು ವರದಿ ಮಾಡಲಾದ ವರ್ಗ',
    'dash_category_distribution': 'ವರ್ಗ ವಿತರಣೆ',
    'dash_complaint_trend': 'ದೂರು ಪ್ರವೃತ್ತಿ (ಈ ವಾರ)',
    'dash_priority_breakdown': 'ಆದ್ಯತೆಯ ವಿಭಜನೆ',
    'dash_complaints_by_category': 'ವರ್ಗದ ಪ್ರಕಾರ ದೂರುಗಳು',

    // Submit Complaint
    'sub_header': 'ಹೊಸ ದೂರು ಸಲ್ಲಿಸಿ',
    'sub_subtitle': 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ, AI ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವರ್ಗೀಕರಿಸುತ್ತದೆ ಮತ್ತು ಆದ್ಯತೆಯನ್ನು ಊಹಿಸುತ್ತದೆ.',
    'sub_title_label': 'ದೂರಿನ ಶೀರ್ಷಿಕೆ',
    'sub_title_placeholder': 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸುವ ಸಣ್ಣ ಶೀರ್ಷಿಕೆ',
    'sub_desc_label': 'ವಿವರವಾದ ವಿವರಣೆ',
    'sub_desc_placeholder': 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರವಾಗಿ ವಿವರಿಸಿ. ಏನು, ಎಲ್ಲಿ, ಯಾವಾಗ ಮತ್ತು ತೀವ್ರತೆಯನ್ನು ಸೇರಿಸಿ. ಹೆಚ್ಚಿನ ವಿವರಗಳನ್ನು ನೀಡಿದರೆ AI ವರ್ಗೀಕರಣವು ಉತ್ತಮವಾಗಿರುತ್ತದೆ...',
    'sub_location_label': 'ಸ್ಥಳ',
    'sub_location_placeholder': 'ಸಮಸ್ಯೆಯ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'sub_image_label': 'ಚಿತ್ರವನ್ನು ಲಗತ್ತಿಸಿ (ಐಚ್ಛಿಕ)',
    'sub_btn_analyze': 'AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ',
    'sub_btn_analyzing': 'GenAI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'sub_btn_submit': 'ದೂರು ಸಲ್ಲಿಸಿ',
    'sub_btn_submitting': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'sub_voice_lang': 'ಮಾತನಾಡುವ ಭಾಷೆ',
    'sub_voice_title': 'ಧ್ವನಿ ಸಹಾಯಕ (ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್)',
    'sub_voice_listen': '🔴 ಕೇಳುತ್ತಿದೆ... ಮಾತನಾಡಿ',
    'sub_voice_processing': '⏳ AI ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿದೆ...',
    'sub_voice_stop': 'ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ — ನಿಲ್ಲಿಸಲು ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ',
    'sub_voice_captured': 'ಭಾಷಣ ರೆಕಾರ್ಡ್ ಆಗಿದೆ! ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಭಾಷಾಂತರಿಸಲಾಗುತ್ತಿದೆ...',
    'sub_voice_tap': 'ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ದೂರನ್ನು ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ',
    'sub_voice_listening_msg': '🎙️ ಡೀಪ್‌ಗ್ರಾಮ್ ಮೂಲಕ ಕೇಳುತ್ತಿದೆ... ಮಾತನಾಡಿ',
    'sub_ai_panel_title': 'AI ವಿಶ್ಲೇಷಣೆ',
    'sub_ai_panel_desc': 'ನಿಮ್ಮ ದೂರಿನ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ವರ್ಗೀಕರಣ, ಆದ್ಯತೆಯ ಮುನ್ಸೂಚನೆ ಮತ್ತು ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಿಯಾ ಯೋಜನೆಯನ್ನು ಪಡೆಯಲು "AI ನೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ" ಕ್ಲಿಕ್ ಮಾಡಿ.',
    'sub_ai_results': '🤖 AI ವಿಶ್ಲೇಷಣೆಯ ಫಲಿತಾಂಶಗಳು',
    'sub_ai_confidence': 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
    'sub_ai_predicted_cat': 'ಊಹಿಸಲಾದ ವರ್ಗ',
    'sub_ai_priority': 'ಆದ್ಯತೆಯ ಮಟ್ಟ',
    'sub_ai_summary': 'AI ಸಾರಾಂಶ',
    'sub_ai_sops': 'ಪಡೆಯಲಾದ SOPಗಳು (RAG)',
    'sub_ai_action_plan': 'ರಚಿಸಲಾದ ಕ್ರಿಯಾ ಯೋಜನೆ',

    // Profile
    'prof_header': 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'prof_lang_label': 'ಆದ್ಯತೆಯ ವೆಬ್‌ಸೈಟ್ ಭಾಷೆ',
    'prof_save': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'prof_saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'prof_details': 'ಖಾತೆ ವಿವರಗಳು',
    'prof_email': 'ಇಮೇಲ್',
    'prof_fullname': 'ಪೂರ್ಣ ಹೆಸರು',
    'prof_dept': 'ವಿಭಾಗ',
    'prof_id': 'ಐಡಿ ಸಂಖ್ಯೆ',
    'prof_phone': 'ದೂರವಾಣಿ',
    'prof_since': 'ಸದಸ್ಯತ್ವದ ದಿನಾಂಕ',
    'prof_edit': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'prof_cancel': 'ರದ್ದುಮಾಡು',
    'prof_administrator': 'ನಿರ್ವಾಹಕರು',
    'prof_student': 'ವಿದ್ಯಾರ್ಥಿ',
    'prof_staff': 'ಸಿಬ್ಬಂದಿ',
    'prof_not_set': 'ಹೊಂದಿಸಿಲ್ಲ'
  }
};

// Helper hook or function to fetch localized key
export function getTranslation(lang, key) {
  const currentLang = TRANSLATIONS[lang] ? lang : 'en-IN';
  return TRANSLATIONS[currentLang][key] || TRANSLATIONS['en-IN'][key] || key;
}
